#!/usr/bin/env bash

# config structure are still under dev.
# this might subject to change at any time.

ENV=$1
if [ -z $ENV ]; then
  echo "usage: ./build <env-name> <cfg-name> <out-name>"
  echo
  echo "following files will be used:"
  echo " - nginx/<env-name>.yaml ( use 'config' for demonstration config ) "
  echo " - nginx/<cfg-name>.ngx ( default config.ngx )"
  echo " - output to config/gen/nginx/<out-name>.ngx ( default config.ngx )"
  echo
  echo "with proper config, a nginx config file will be generated at config/gen/nginx/<out-name>.ngx"
  echo
  exit
fi

CFG=$2
if [ -z $CFG ]; then
  CFG=config
fi
OUT=$3
if [ -z $OUT ]; then
  OUT=config
fi

mkdir -p ../gen/nginx
npx tt -c nginx/$ENV.yaml -o ../gen/nginx/$OUT.ngx nginx/$CFG.ngx
echo "config/gen/nginx/$OUT.ngx generated"
