#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "build auth.ls -> auth.js ..."
npx lsc -cp src/auth.ls > dist/index.js
echo "minify auth.js -> auth.min.js ..."
npx uglifyjs dist/index.js > dist/index.min.js

echo "build authpanel.pug ..."
npx srcbuild-pug src/authpanel.pug > dist/index.html
