#!/usr/bin/env bash
trap "kill 0" exit

# pino-pretty params
#  -i : ignore
#  -c : color
#  -t : format timestamp

# TODO This should be done via some kind of service
while [ 1 ]; do
  # production
  #node ./.engine/index.js | \
  #    tee -a ./server.log | \
  #    ./node_modules/.bin/pino-pretty \
  #      -c -o "[{module}] {msg} {responseTime}" \
  #      -i req,res,hostname,pid,module,responseTime \
  #      -t "yyyy/mm/dd HH:MM:sso"

  # dev
  ./node_modules/.bin/lsc ./engine/index | \
     tee -a server.log | \
     ./node_modules/.bin/pino-pretty \
       -c -o "[{module}] {msg} {responseTime}" \
       -i req,res,hostname,pid,module,responseTime \
       -t "yy/mm/dd HH:MM:sso"

  echo "server down; try to auto restart after 1s."
  sleep 1;
done

wait
