#!/usr/bin/env bash
trap "kill 0" exit

# pino-pretty params
#  -i : ignore
#  -c : color
#  -t : format timestamp

# TODO We probably should do this via some kind of service / package
while [ 1 ]; do

  if [[ $NODE_ENV == "production" ]]; then
    # production - use prebuilt js files
    CMD="node ./.engine/index.js"
  else
    # dev - use livescript files
    CMD="./node_modules/.bin/lsc ./engine/index"
  fi

  $CMD | \
     tee -a server.log | \
     ./node_modules/.bin/pino-pretty \
       -c -o "[{module}] {msg} {responseTime}" \
       -i req,res,hostname,pid,module,responseTime \
       -t "yy/mm/dd HH:MM:sso"

  echo "server down; try to auto restart after 1s."
  sleep 1;
done

wait
