#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building consent.ls -> consent.js ..."
npx lsc -cp src/consent.ls > dist/consent.js
echo "minify consent.js -> consent.min.js ..."
npx uglifyjs dist/consent.js > dist/consent.min.js

echo "build src/consent.styl -> dist/consent.css ..."
./node_modules/.bin/stylus -p src/consent.styl > dist/consent.css
echo "minifying consent.css ..."
./node_modules/.bin/uglifycss dist/consent.css > dist/consent.min.css

echo "copy dist to web ..."
rm -rf web/static/assets/lib/consent/dev/
mkdir -p web/static/assets/lib/consent/dev/
cp -R dist/* web/static/assets/lib/consent/dev/
