#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building consent.ls -> index.js ..."
./node_modules/.bin/lsc -cp --no-header src/consent.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js

echo "build consent base ..."
mkdir -p dist/block/base/0.0.1
./node_modules/.bin/srcbuild-pug src/block/base/0.0.1/index.pug > dist/block/base/0.0.1/index.html

echo "build cookie consent  ..."
mkdir -p dist/block/cookie/0.0.1
./node_modules/.bin/srcbuild-pug src/block/cookie/0.0.1/index.pug > dist/block/cookie/0.0.1/index.html

echo "build tos consent  ..."
mkdir -p dist/block/tos/0.0.1
./node_modules/.bin/srcbuild-pug src/block/tos/0.0.1/index.pug > dist/block/tos/0.0.1/index.html

echo "build server files ..."
node_modules/.bin/lsc -co dist/lib lib
