#!/bin/bash

file_pug="module/base/version/index.pug"
file_version=".version"

## with branch name
# echo -n $(git rev-parse --abbrev-ref HEAD) > $file_version
# echo -n "-" >> $file_version
# echo -n $(git describe --always) >> $file_version
## without branch name
echo -n $(git describe --always) > $file_version

echo "//- module" > $file_pug
echo -n "- var version = \"" >> $file_pug
echo -n $(git describe --always) >> $file_pug
echo "\";" >> $file_pug
exec git add $file_version $file_pug

