#!/usr/bin/env bash

# config structure are still under dev.
# this might subject to change at any time.

ENV=$1
if [ -z $ENV ]; then
  echo "usage: ./build <env-name>"
  echo "nginx/<env-name>.yaml will be used"
  exit
fi

mkdir -p gen/nginx
npx tt -c nginx/$ENV.yaml -o gen/nginx/config.ngx nginx/config.ngx

