#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "build index.ls -> index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js

