// Generated by LiveScript 1.6.0
(function(){
  var fs, colors, jsYaml, lderror, nodemailer, nodemailerMailgunTransport, md, mailQueue;
  fs = require('fs');
  colors = require('@plotdb/colors');
  jsYaml = require('js-yaml');
  lderror = require('lderror');
  nodemailer = require('nodemailer');
  nodemailerMailgunTransport = require('nodemailer-mailgun-transport');
  md = require('./utils/md');
  mailQueue = function(opt){
    var this$ = this;
    opt == null && (opt = {});
    this.api = !opt.mailgun
      ? {
        sendMail: function(){
          this$.log.error("sendMail called while mail gateway is not available");
          return lderror.reject(500, "mail service not available");
        }
      }
      : nodemailer.createTransport(nodemailerMailgunTransport(opt.mailgun));
    this.base = opt.base || 'base';
    this.log = opt.logger;
    this.list = [];
    return this;
  };
  mailQueue.prototype = import$(Object.create(Object.prototype), {
    add: function(obj){
      this.list.push(obj);
      return this.handler();
    },
    handle: null,
    handler: function(){
      var this$ = this;
      if (this.handle) {
        return;
      }
      this.log.info("new job incoming, handling...".cyan);
      return this.handle = setInterval(function(){
        var obj;
        this$.log.info((this$.list.length + " jobs remain...").cyan);
        obj = this$.list.splice(0, 1)[0];
        if (!obj) {
          this$.log.info("all job done, take a rest.".green);
          clearInterval(this$.handle);
          this$.handle = null;
          return;
        }
        return this$.sendDirectly(obj.payload).then(obj.res)['catch'](obj.rej);
      }, 5000);
    },
    send: function(payload, opt){
      var this$ = this;
      opt == null && (opt = {});
      if (opt.now) {
        return this.sendDirectly(payload);
      }
      return new Promise(function(res, rej){
        return this$.add({
          payload: payload,
          res: res,
          rej: rej
        });
      });
    },
    sendDirectly: function(payload){
      var this$ = this;
      return new Promise(function(res, rej){
        this$.log.info(("sending [from:" + payload.from + "] [to:" + payload.to + "] [subject:" + payload.subject + "]").cyan);
        return this$.api.sendMail(payload, function(e, i){
          if (!e) {
            return res();
          }
          this$.log.error("send mail failed: api.sendMail failed.", e);
          return rej(lderror(500));
        });
      });
    },
    sendFromMd: function(payload, map, opt){
      var this$ = this;
      map == null && (map = {});
      opt == null && (opt = {});
      return new Promise(function(res, rej){
        var content, k, ref$, v, re;
        content = payload.content || '';
        for (k in ref$ = map) {
          v = ref$[k];
          re = new RegExp("#{" + k + "}", "g");
          content = content.replace(re, v);
          payload.from = payload.from.replace(re, v);
          payload.subject = payload.subject.replace(re, v);
        }
        payload.text = md.toText(content);
        payload.html = md.toHtml(content);
        delete payload.content;
        return this$.send(payload, opt).then(function(){
          return res();
        });
      });
    },
    byTemplate: function(name, email, map, config){
      var fn, path, that, this$ = this;
      map == null && (map = {});
      config == null && (config = {});
      fn = function(b){
        return "config/" + b + "/mail/" + name + ".yaml";
      };
      path = (that = config.path) ? that : '.';
      return fs.promises.access(fn(this.base)).then(function(){
        return fn(this$.base);
      })['catch'](function(){
        return fs.promises.access(fn('base')).then(function(){
          return fn('base');
        });
      })['catch'](function(){
        this$.log.error("send mail failed: read template file failed.", e);
        return lderror.reject(1027);
      }).then(function(file){
        return fs.promises.readFile(file)['catch'](function(e){
          this$.log.error("send mail failed: read template file failed. ", e);
          return lderror.reject(1017);
        });
      }).then(function(content){
        var e;
        try {
          return jsYaml.safeLoad(content);
        } catch (e$) {
          e = e$;
          this$.log.error("send mail failed: parse template yaml failed.", e);
          return lderror.reject(1017);
        }
      }).then(function(payload){
        var option;
        option = {
          from: payload.from,
          to: email,
          subject: payload.subject,
          content: payload.content
        };
        if (config.bcc) {
          option.bcc = config.bcc;
        }
        return this$.sendFromMd(option, map, {
          now: config.now
        });
      });
    }
  });
  module.exports = mailQueue;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
