// Generated by LiveScript 1.6.0
(function(){
  var fs, path, lderror, aux, express;
  fs = require('fs');
  path = require('path');
  lderror = require('lderror');
  aux = require('backend/aux');
  express = require('express');
  (function(it){
    return module.exports = it;
  })(function(backend){
    var db, config, ref$, api, app, demoApi, demoApp;
    db = backend.db, config = backend.config, ref$ = backend.route, api = ref$.api, app = ref$.app;
    demoApi = aux.routecatch(express.Router({
      mergeParams: true
    }));
    demoApp = aux.routecatch(express.Router({
      mergeParams: true
    }));
    api.use('/demo', demoApi);
    app.use('/demo', demoApp);
    return fs.readdirSync(__dirname).filter(function(it){
      return !/^index\./.exec(it);
    }).filter(function(it){
      return !/^\./.exec(it);
    }).map(function(it){
      return path.join(__dirname, it);
    }).filter(function(it){
      return /\.(ls|js)$/.exec(it) || fs.statSync(it).isDirectory();
    }).map(function(it){
      return require(it)(backend, {
        api: demoApi,
        app: demoApp
      });
    });
  });
}).call(this);
