// Generated by LiveScript 1.6.0
(function(){
  var fs, path, lderror, aux;
  fs = require('fs');
  path = require('path');
  lderror = require('lderror');
  aux = require('backend/aux');
  (function(it){
    return module.exports = it;
  })(function(backend){
    var db, config, ref$, api, app;
    db = backend.db, config = backend.config, ref$ = backend.route, api = ref$.api, app = ref$.app;
    app.get('/demo/', function(req, res, next){
      return db.query("select count(key) as count from users").then(function(r){
        var count;
        r == null && (r = {});
        count = ((r.rows || (r.rows = []))[0] || {
          count: 0
        }).count;
        return res.render('/demo/index.pug', {
          count: count
        });
      });
    });
    app.get('/demo/i18n', function(req, res, next){
      return res.send({
        locale: req.get("I18n-Locale")
      });
    });
    api.get('/demo/error', function(req, res, next){
      throw new Error();
    });
    app.get('/demo/error', function(req, res, next){
      throw new Error();
    });
    api.get('/demo/error/next', function(req, res, next){
      return next(new Error());
    });
    app.get('/demo/error/next', function(req, res, next){
      return next(new Error());
    });
    api.get('/demo/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/demo/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/demo/error/reject', function(req, res, next){
      return Promise.reject(new Error());
    });
    return app.get('/demo/lderror/reject', function(req, res, next){
      return Promise.reject(lderror(1023));
    });
  });
}).call(this);
