// Generated by LiveScript 1.6.0
(function(){
  var fs, path, lderror, aux, throttle;
  fs = require('fs');
  path = require('path');
  lderror = require('lderror');
  aux = require('backend/aux');
  throttle = require('backend/throttle');
  (function(it){
    return module.exports = it;
  })(function(backend, arg$){
    var api, app, db, config;
    api = arg$.api, app = arg$.app;
    db = backend.db, config = backend.config;
    app.get('/', throttle.kit.generic, function(req, res, next){
      return db.query("select count(key) as count from users").then(function(r){
        var count;
        r == null && (r = {});
        count = ((r.rows || (r.rows = []))[0] || {
          count: 0
        }).count;
        return res.render('index.pug', {
          count: count
        });
      });
    });
    app.get('/i18n', function(req, res, next){
      return res.send({
        locale: req.get("I18n-Locale")
      });
    });
    api.get('/error', function(req, res, next){
      throw new Error();
    });
    app.get('/error', function(req, res, next){
      throw new Error();
    });
    api.get('/error/next', function(req, res, next){
      return next(new Error());
    });
    app.get('/error/next', function(req, res, next){
      return next(new Error());
    });
    api.get('/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/lderror', function(req, res, next){
      return next(lderror(1023));
    });
    app.get('/error/reject', function(req, res, next){
      return Promise.reject(new Error());
    });
    app.get('/lderror/reject', function(req, res, next){
      return Promise.reject(lderror(1023));
    });
    return api.get('/ip', function(req, res, next){
      return res.send(aux.ip(req));
    });
  });
}).call(this);
