// Generated by LiveScript 1.6.0
(function(){
  var throttle, aux, key;
  throttle = require("./core");
  aux = require('../aux');
  key = {
    ip: function(req){
      return aux.ip(req) + ":" + req.baseUrl + req.path;
    },
    user: function(req){
      return (req.user ? req.user.key : 0) + ":" + req.baseUrl + req.path;
    },
    ipUser: function(req){
      return aux.ip(req) + ":" + (req.user ? req.user.key : 0) + ":" + req.baseUrl + req.path;
    }
  };
  module.exports = {
    signup: throttle({
      span: 10 * 60 * 1000,
      maxCount: 10,
      delayCount: 5,
      delay: 400,
      key: key.ip
    }),
    login: throttle({
      span: 1 * 60 * 1000,
      maxCount: 20,
      delayCount: 5,
      delay: 200,
      key: key.ip
    }),
    generic: throttle({
      span: 1 * 60 * 1000,
      maxCount: 30,
      delayCount: 15,
      delay: 200,
      key: key.user
    }),
    key: key
  };
}).call(this);
