// Generated by LiveScript 1.6.0
(function(){
  var base;
  base = {
    ip: function(req){
      return req.headers['cf-connecting-ip'] || req.headers['x-forwarded-for'] || req.headers['X-Real-IP'] || req.headers['x-real-ip'] || req.connection.remoteAddress;
    },
    autocatch: function(handler){
      return function(req, res, next){
        var ret;
        ret = handler(req, res, next);
        if (!(ret instanceof Promise)) {
          return next(new Error('autocatch is used yet return value of callback is not a Promise.'));
        } else {
          return ret['catch'](function(it){
            return next(it);
          });
        }
      };
    },
    authedView: function(req, res, next){
      if (req.user && req.user.key > 0) {
        return next();
      }
      return res.status(403).redirect("/auth/?nexturl=/" + req.originalUrl);
    },
    reject: function(code, msg){
      var ref$;
      code == null && (code = 403);
      msg == null && (msg = "");
      return Promise.reject((ref$ = new Error(typeof msg === typeof {} ? JSON.stringify(msg) : msg), ref$.code = code, ref$.name = 'lderror', ref$));
    }
  };
  module.exports = base;
}).call(this);
