// Generated by LiveScript 1.6.0
(function(){
  var base;
  base = {
    ip: function(req){
      return req.headers['cf-connecting-ip'] || req.headers['x-forwarded-for'] || req.headers['X-Real-IP'] || req.headers['x-real-ip'] || req.connection.remoteAddress;
    },
    autocatch: function(handler){
      return function(req, res, next){
        var ret;
        ret = handler(req, res, next);
        if (!(ret instanceof Promise)) {
          return next(new Error('autocatch is used yet return value of callback is not a Promise.'));
        } else {
          return ret['catch'](function(it){
            return next(it);
          });
        }
      };
    }
  };
  module.exports = base;
}).call(this);
